version: "3.8"
services:
    tm:
        build: ./TM
        image: tm:tmapp
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - postgresql
            - tm-api
    tm-api:
        build: ./TM.API
        image: tm-api:tmapi
        restart: always
        ports:
            - "5000:80"
        depends_on:
            - postgresql
    postgresql:
        build: ./DB
        image: postgresql:pgsql-server
        restart: always        
        environment:
            POSTGRES_DB: "TimeManagementDB"
            POSTGRES_USER: "vestas"
            POSTGRES_PASSWORD: "vestas"
            PGDATA: /var/lib/postgresql/data
        ports:
            - "15000:5432"
        volumes:
            - ./DB/pgsqldata:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: "pgadmin@example.com"
            PGADMIN_DEFAULT_PASSWORD: "admin2020!"
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "16000:80"
        volumes:
            - ./DB/pgadmin:/var/lib/pgadmin
        depends_on:
            - postgresql
        
volumes:
    datadir:
    pgadmin-data:
