name: Calculate Next Version
on:
  pull_request:
    branches:
      - main
jobs:
  NextVersionCalculation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.0.0'
      - name: Determine Version
        id: version_calculated # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true
          configFilePath: ./git-version-config.yaml
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Automated Versioning 

              After merging this PR, the next version will be: '**${{ steps.version_calculated.outputs.MajorMinorPatch }}**'

              `
            })